### ISSUE TITLE
Installing CLI on MacOS with Brew

### ISSUE THREAD

**Issue by fideseo-llc** [CheckPointSW/harmony-endpoint-management-cli#5]
Is there specific instructions for installing the CLI using Brew on MacOS?

**Comment by chkp-haimk** [comment]
Hi @fideseo-llc 
Currently no, it's just a package in Python's PIP repository.

 You need to install Python with PIP and install it via PIP.

**Comment by chkp-haimk** [comment]
I'm closing it for now.
Please feel free to re-open the issue if there are further questions/issues regarding this topic.
